### ISSUE TITLE
Корзина

### ISSUE THREAD

**Issue by usvladis** [usvladis/FakeNFT_team3#35]
Модуль 1:

- [x] usvladis/FakeNFT_team3/issues/1
- [x] usvladis/FakeNFT_team3/issues/2
- [x] usvladis/FakeNFT_team3/issues/3
- [x] usvladis/FakeNFT_team3/issues/4
- [x] usvladis/FakeNFT_team3/issues/5
- [x] usvladis/FakeNFT_team3/issues/6

Модуль 2:

- [x] usvladis/FakeNFT_team3/issues/7
- [x] usvladis/FakeNFT_team3/issues/8
- [x] usvladis/FakeNFT_team3/issues/9
- [x] usvladis/FakeNFT_team3/issues/10
- [x] usvladis/FakeNFT_team3/issues/11

Модуль 3:

- [ ] usvladis/FakeNFT_team3/issues/12
- [ ] usvladis/FakeNFT_team3/issues/13
- [ ] usvladis/FakeNFT_team3/issues/14
- [ ] usvladis/FakeNFT_team3/issues/15
- [ ] usvladis/FakeNFT_team3/issues/16
